import {setupExperiment} from '../../balance-checkpoint/equal-turns/source/scripts/balance/experiment';
import {BotTracker} from '../../src/lib/bots/session';
import {decide} from '../../src/lib/bots/policy';
import {applyPlayCommand,standings} from '../../src/lib/game/actions';
import {ok} from 'node:assert';
const {game}=setupExperiment('diagnostic-closing-fixture',['melia','doreios'],'standard');const g=game as any;g.publicActivity=[];g.turn.equalTurns=true;g.turn.index=1;g.turn.number=20;g.turn.phase='buys';
const [other,uid]=g.turnOrder;g.turn.turns={[other]:10,[uid]:9};g.resources={actions:0,buys:1,coins:4,worship:1};
const cards=(ids:string[],who:string)=>ids.map((cardId,i)=>({id:who+'-'+i,cardId,copy:i}));
g.decks[other]={hand:[],deck:cards(['acropolis','acropolis'],other),discard:[],play:[]};
const owned=cards(['acropolis','acropolis','acropolis','temple-of-ares',...Array(6).fill('obol'),...Array(3).fill('drachma')],uid);
g.decks[uid]={hand:[owned[0]],deck:owned.slice(1),discard:[],play:[]};g.supply.acropolis=1;
const tracker=new BotTracker(g);
for(const p of g.turnOrder)tracker.inventory[p]=Object.values(g.decks[p]).flat().reduce((a:any,c:any)=>(a[c.cardId]=(a[c.cardId]??0)+1,a),{});
const v=tracker.view(g);
const historical=decide(v,{turn:10},'classic-engine'),current=decide(v,{turn:10},'engine'),money=decide(v,{turn:10},'money');
applyPlayCommand(g,uid,{type:'god/worshipped',cardId:'trial-of-the-spear'},1);
applyPlayCommand(g,uid,{type:'choice/resolved',choiceId:g.turn.choice.id,targets:[owned[0].id]},2);
applyPlayCommand(g,uid,{type:'choice/resolved',choiceId:g.turn.choice.id,targets:['acropolis']},3);
applyPlayCommand(g,uid,{type:'turn/ended'},4);
ok(g.turn.phase==='finished'&&standings(g).find(x=>x.uid===uid)?.winner);
ok(historical.type!=='god/worshipped');
console.log(JSON.stringify({description:'Controlled legal P2 closing position: Doreios 18 VP vs 12, $4, Acropolis in hand, one Acropolis left',historical,current,money,winningContinuation:'Trial of the Spear -> trash Acropolis -> gain Acropolis -> end turn',final:standings(g)},null,2));
