import {enterTreasures,browseSupply} from '../helpers/supply-controls';
import {test,expect} from '../helpers/fixtures';
import {TestStepHelper} from '../helpers/test-step-helper';
import {roomCodeFixture} from '../helpers/room-code-fixture';
import {newPlayerContext} from '../helpers/players';
import {readEvents} from '../helpers/action-history';
import {replaySetup} from '../../../src/lib/game/setup';
import type {Page} from '@playwright/test';

test('keep playing a Temple, spend the last Buy, and hand the turn to a friend exactly once',async({page,browser},info)=>{
  const context=await newPlayerContext(browser,{viewport:info.project.use.viewport,baseURL:info.project.use.baseURL}),other=await context.newPage(),steps=new TestStepHelper(page,info,'Finish a turn together');
  const capture=(id:string,text:string,client:Page,player:string,check:()=>Promise<unknown>)=>steps.step(id,text,[{spec:text,check}],{page:client,player});
  try{
    const code=await roomCodeFixture(page,info,'worship-story-2');
    await page.goto('./play/');
    await capture('gather','Ariadne opens a two-player table',page,'Ariadne',async()=>expect(page.getByRole('button',{name:'Create table',exact:true})).toBeEnabled());
    await page.getByLabel('Your name',{exact:true}).fill('Ariadne');await page.getByRole('button',{name:'Create table',exact:true}).click();
    await capture('waiting','Ariadne waits for her friend',page,'Ariadne',async()=>expect(page.getByTestId('player-seat')).toHaveCount(1));
    await other.goto(page.url());await other.getByLabel('Your name',{exact:true}).fill('Theseus');await other.getByRole('button',{name:'Join table',exact:true}).click();
    await capture('together','Theseus joins Ariadne’s table',page,'Ariadne',async()=>expect(page.getByRole('button',{name:'Begin',exact:true})).toBeEnabled());
    await page.getByRole('button',{name:'Begin',exact:true}).click();
    await capture('draft','Theseus chooses his bloodline first',other,'Theseus',async()=>expect(other.getByRole('button',{name:'Choose Thaleia',exact:true})).toBeEnabled());
    await other.getByRole('button',{name:'View Nereon',exact:true}).click();
    await capture('nereon','Theseus considers Nereon’s Temple and god',other,'Theseus',async()=>expect(other.getByRole('button',{name:'Choose Nereon',exact:true})).toBeEnabled());
    await other.getByRole('button',{name:'Choose Nereon',exact:true}).click();
    await capture('thaleia','Ariadne chooses Thaleia for her empire',page,'Ariadne',async()=>expect(page.getByRole('button',{name:'Choose Thaleia',exact:true})).toBeEnabled());
    await page.getByRole('button',{name:'Choose Thaleia',exact:true}).click();
    await capture('hand','Ariadne receives a Temple and four Obols',page,'Ariadne',async()=>{await expect(page.locator('.hand [data-card-id="temple-of-athena"]')).toHaveCount(1);await expect(page.locator('.hand [data-card-id="obol"]')).toHaveCount(4);});
    const index=await page.locator('.hand [data-card-id="temple-of-athena"]').evaluate(node=>[...node.closest('.hand')!.querySelectorAll('[data-card-id]')].indexOf(node));await page.getByTestId('hand-card').nth(index).click({button:'right'});
    await capture('temple','The Temple can be read before it is played',page,'Ariadne',async()=>expect(page.getByRole('button',{name:'Play Temple of Athena',exact:true})).toBeEnabled());
    await page.getByRole('button',{name:'Play Temple of Athena',exact:true}).click();
    await capture('played','The Temple and Thaleia leave two Actions and two Worship',page,'Ariadne',async()=>{await expect(page.locator('.resources [data-resource=actions]')).toHaveAttribute('data-value','2');await expect(page.locator('.resources [data-resource=worship]')).toHaveAttribute('data-value','2');});
    await enterTreasures(page);
    await capture('treasures','Ariadne can now play her wealth',page,'Ariadne',async()=>expect(page.getByRole('button',{name:'Play all Treasures',exact:true})).toBeEnabled());
    await page.getByRole('button',{name:'Play all Treasures',exact:true}).click();
    await capture('wealth','Four Obols provide four Coins',page,'Ariadne',async()=>expect(page.locator('.resources [data-resource=coins]')).toHaveAttribute('data-value','4'));
    await page.getByRole('button',{name:'Supply',exact:true}).click();
    await capture('supply','The supply offers both Basics and Actions',page,'Ariadne',async()=>expect(page.locator('.coverflow')).toBeVisible());
    await browseSupply(page,'Council of Sages');
    await capture('actions','Ariadne explores Action cards',page,'Ariadne',async()=>expect(page.getByRole('button',{name:'Buy Council of Sages',exact:true})).toBeVisible());
    await capture('council','Council of Sages costs all four Coins',page,'Ariadne',async()=>expect(page.getByRole('button',{name:'Buy Council of Sages',exact:true})).toBeEnabled());
    await page.getByRole('button',{name:'Buy Council of Sages',exact:true}).click();
    await capture('last-buy','Spending the last Buy does not end the turn',page,'Ariadne',async()=>expect(page.locator('.wallet [data-resource=buys]')).toHaveAttribute('data-value','0'));
    await page.getByRole('button',{name:'‹ Table',exact:true}).click();
    await capture('finish','Ariadne chooses when to finish her turn',page,'Ariadne',async()=>{await expect(page.locator('.turn-marker')).toContainText('Buys');await expect(page.getByRole('button',{name:'End turn',exact:true})).toBeEnabled();});
    await page.emulateMedia({reducedMotion:'no-preference'});await other.emulateMedia({reducedMotion:'no-preference'});
    let dropped=false;await page.context().route(url=>url.pathname.endsWith('/documents:commit'),async route=>{if(dropped){await route.continue();return;}const response=await route.fetch({timeout:2000});expect(response.ok()).toBe(true);dropped=true;await route.abort('connectionreset');});
    await page.getByRole('button',{name:'End turn',exact:true}).click();
    await capture('handoff','Theseus receives fresh counters after public cleanup finishes',other,'Theseus',async()=>{await expect(other.locator('.turn-marker')).toContainText('Your turn');await expect(other.locator('.resources [data-resource=actions]')).toHaveAttribute('data-value','1');await expect(other.locator('.resources [data-resource=coins]')).toHaveAttribute('data-value','0');await expect(other.locator('.resources [data-resource=worship]')).toHaveAttribute('data-value','1');await expect(other.getByRole('button',{name:'End turn',exact:true})).toBeEnabled();await other.waitForFunction(()=>!document.querySelector('.public-flight'),undefined,{polling:20,timeout:2000});});
    await capture('waiting-hand','Ariadne receives five private cards and waits for Theseus',page,'Ariadne',async()=>{await expect(page.locator('.turn-marker')).toContainText('Theseus');await expect(page.getByTestId('hand-card')).toHaveCount(5);await expect(page.locator('.opponents [data-card-id]')).toHaveCount(0);await expect(page.getByRole('button',{name:'End turn',exact:true})).toHaveCount(0);});
    const events=await readEvents(code),state=replaySetup(events),host=events[0].actorUid;expect(dropped).toBe(true);expect(events.filter(e=>e.type==='turn/ended')).toHaveLength(1);expect(state.turn.turns[host]).toBe(1);expect(state.decks[host].play).toHaveLength(0);expect(state.decks[host].discard).toHaveLength(6);expect(state.decks[host].hand.filter(c=>c.cardId==='hamlet')).toHaveLength(3);
    await page.reload();
    await capture('return','Returning does not repeat cleanup or draw another hand',page,'Ariadne',async()=>expect(page.locator('.turn-marker')).toContainText('Theseus'));
    expect(replaySetup(await readEvents(code))).toEqual(state);
  }finally{await context.close();}
});
