import {browseSupply,enterTreasures} from '../helpers/supply-controls';
import {test,expect} from '../helpers/fixtures';
import {newPlayerContext} from '../helpers/players';
import {roomCodeFixture} from '../helpers/room-code-fixture';
import {TestStepHelper} from '../helpers/test-step-helper';
import {readEvents} from '../helpers/action-history';
import {replaySetup} from '../../../src/lib/game/setup';

test('follow a friend from the first Temple through Worship and cleanup while reading the public table',async({page,browser},info)=>{
  test.setTimeout(180_000);
  const context=await newPlayerContext(browser,{viewport:info.project.use.viewport,baseURL:info.project.use.baseURL});
  const other=await context.newPage(),steps=new TestStepHelper(page,info,'Follow a friend at the public table');
  const errors:string[]=[];for(const client of [page,other])client.on('pageerror',error=>errors.push(error.message));
  const capture=(id:string,text:string,check:()=>Promise<unknown>,observer=false)=>steps.step(id,text,[{spec:text,check}],{page:observer?other:page,player:observer?'Theseus':'Ariadne'});
  try{
    const code=await roomCodeFixture(page,info,'worship-story-2');
    await page.goto('./play/');await page.getByLabel('Your name',{exact:true}).fill('Ariadne');await page.getByRole('button',{name:'Create table',exact:true}).click();
    await capture('created','Ariadne invites Theseus to a two-player table',async()=>expect(page.getByTestId('room-code')).toHaveText(code));
    await other.goto(page.url());await other.getByLabel('Your name',{exact:true}).fill('Theseus');await other.getByRole('button',{name:'Join table',exact:true}).click();
    await capture('joined','Both friends are seated and Ariadne can begin',async()=>expect(page.getByRole('button',{name:'Begin',exact:true})).toBeEnabled());
    await page.getByRole('button',{name:'Begin',exact:true}).click();
    await capture('draft','Theseus chooses Thaleia first',async()=>expect(other.getByRole('button',{name:'Choose Thaleia',exact:true})).toBeEnabled(),true);
    await other.getByRole('button',{name:'Choose Thaleia',exact:true}).click();await page.getByRole('button',{name:'View Nereon',exact:true}).click();
    await capture('nereon','Ariadne chooses Nereon and the Temple of Poseidon',async()=>expect(page.getByRole('button',{name:'Choose Nereon',exact:true})).toBeEnabled());
    await page.getByRole('button',{name:'Choose Nereon',exact:true}).click();
    await capture('opening','Ariadne holds her Temple and four Obols',async()=>expect.poll(()=>page.locator('.hand [data-card-id]').evaluateAll(nodes=>nodes.map(node=>node.getAttribute('data-card-id')))).toEqual(['temple-of-poseidon','obol','obol','obol','obol']));
    await capture('observer','Theseus sees whose turn it is and only common backs for Ariadne’s hand',async()=>{await expect(other.locator('.turn-marker')).toContainText('Ariadne');await expect(other.locator('.opponents [data-card-id]')).toHaveCount(0);},true);
    await page.getByTestId('hand-card').first().click({button:'right'});
    await capture('temple','Ariadne reads her Temple before playing it',async()=>expect(page.getByRole('button',{name:'Play Temple of Poseidon',exact:true})).toBeEnabled());
    await page.getByRole('button',{name:'Play Temple of Poseidon',exact:true}).click();
    await capture('played','Theseus sees the Temple, Nereon’s blessing, and the resulting Coin',async()=>{await expect(other.locator('.played-cards [data-card-id]')).toHaveAttribute('data-card-id','temple-of-poseidon');await expect(other.locator('.resources [data-resource=coins]')).toHaveAttribute('data-value','1');await expect(other.locator('.turn-marker')).toContainText('Treasures');},true);
    await other.getByRole('button',{name:'Chronicle',exact:true}).click();
    await capture('chronicle','The Chronicle keeps the played Temple before the leader’s blessing',async()=>{await expect(other.locator('.move')).toHaveCount(2);await expect(other.locator('.move').first()).toHaveAttribute('data-movement','play');await expect(other.locator('.move').last()).toHaveAttribute('data-movement','leader');await expect(other.locator('.result [data-resource=worship]')).toHaveAttribute('data-value','+1');},true);
    await other.getByRole('button',{name:'Inspect Temple of Poseidon, copy 1',exact:true}).click();
    await capture('public-inspector','A public card opens at reading size without offering a play command',async()=>{await expect(other.getByRole('button',{name:'Return to Chronicle',exact:true})).toBeFocused();await expect(other.getByRole('button',{name:'Play Temple of Poseidon',exact:true})).toHaveCount(0);},true);
    await other.keyboard.press('Escape');
    await capture('return-history','Escape returns to the same move and restores card focus',async()=>expect(other.getByRole('button',{name:'Inspect Temple of Poseidon, copy 1',exact:true})).toBeFocused(),true);
    const reading=await other.locator('.chronicle').innerText();
    await enterTreasures(page);
    await page.getByRole('button',{name:'Play all Treasures',exact:true}).click();
    await capture('new-move','Ariadne plays Treasures while Theseus keeps his reading position',async()=>{await expect(other.getByRole('button',{name:'New moves · 1 · Refresh',exact:true})).toBeVisible();await expect(other.locator('.chronicle')).toHaveText(reading,{useInnerText:true});},true);
    await capture('wealth','Ariadne plays four Obols and reaches five Coins',async()=>expect(page.locator('.resources [data-resource=coins]')).toHaveAttribute('data-value','5'));
    await other.getByRole('button',{name:'New moves · 1 · Refresh',exact:true}).click();
    await capture('wealth-history','Theseus explicitly catches up to the played Treasures',async()=>{await expect(other.locator('.move')).toHaveCount(3);await expect(other.getByRole('button',{name:'Next effects',exact:true})).toBeEnabled();},true);
    await other.getByRole('button',{name:'Next effects',exact:true}).click();
    await capture('last-effect','Every Treasure remains reachable at the end of the move',async()=>{await expect(other.locator('.move')).toHaveCount(1);await expect(other.getByRole('button',{name:'Next effects',exact:true})).toBeDisabled();},true);
    await other.getByRole('button',{name:'Discard',exact:true}).click();await other.getByLabel('Player',{exact:true}).selectOption({label:'Ariadne'});
    await capture('empty-pile','Ariadne’s empty discard and hidden deck count are explicit',async()=>{await expect(other.locator('.pile')).toHaveText('No cards here.');await expect(other.locator('.deck-count')).toHaveText('Deck · 5 cards');},true);
    await page.getByRole('button',{name:'Supply',exact:true}).click();await browseSupply(page,'Hamlet');
    await capture('purchase','Ariadne chooses a Hamlet for two Coins',async()=>expect(page.getByRole('button',{name:'Buy Hamlet',exact:true})).toBeEnabled());
    await page.getByRole('button',{name:'Buy Hamlet',exact:true}).click();
    await capture('bought','Ariadne’s purchase goes to discard and leaves three Coins',async()=>expect(page.locator('.wallet [data-resource=coins]')).toHaveAttribute('data-value','3'));
    await capture('stable-pile','Incoming cards do not reorder or replace the open tray',async()=>{await expect(other.locator('.pile')).toHaveText('No cards here.');await expect(other.getByRole('button',{name:'New moves · 1 · Refresh',exact:true})).toBeVisible();},true);
    await other.getByRole('button',{name:'New moves · 1 · Refresh',exact:true}).click();
    await capture('refreshed-pile','Theseus chooses to show the newly purchased Hamlet',async()=>expect(other.locator('.pile [data-card-id]')).toHaveAttribute('data-card-id','hamlet'),true);
    await other.getByRole('button',{name:'Inspect Hamlet, copy 1',exact:true}).click();
    await capture('pile-inspection','The physical Hamlet copy can be read in full',async()=>expect(other.getByRole('button',{name:'Return to pile',exact:true})).toBeFocused(),true);
    await other.getByRole('button',{name:'Return to pile',exact:true}).click();await expect(other.getByRole('button',{name:'Inspect Hamlet, copy 1',exact:true})).toBeFocused();
    await other.getByRole('button',{name:'In play',exact:true}).click();
    await capture('play-pile','All five played cards are available in a stable public tray',async()=>{await expect(other.locator('.pile-count')).toHaveText('5 cards');await expect(other.locator('.pile [data-card-id]')).toHaveCount(3);},true);
    await other.getByRole('button',{name:'Next',exact:true}).click();
    await capture('last-pile-page','The last two played cards are reachable without leaving the table',async()=>{await expect(other.locator('.pile [data-card-id]')).toHaveCount(2);await expect(other.getByRole('button',{name:'Next',exact:true})).toBeDisabled();},true);
    await page.getByRole('button',{name:'‹ Table',exact:true}).click();await page.getByRole('button',{name:'Inspect Counsel of Olympus',exact:true}).click();
    await capture('worship','Ariadne can Worship Athena even after spending her last Buy',async()=>expect(page.getByRole('button',{name:'Worship Athena',exact:true})).toBeEnabled());
    await page.getByRole('button',{name:'Worship Athena',exact:true}).click();
    await capture('gain-choice','Ariadne pays for Worship and chooses a topdeck gain',async()=>expect(page.locator('.choice-scene .destination')).toHaveText('Onto your deck'));
    await page.getByRole('button',{name:'Select Oracle’s Acolyte, copy 1',exact:true}).click();
    await capture('selected-gain','Oracle’s Acolyte is selected as the gift from Athena',async()=>expect(page.getByRole('button',{name:'Gain Oracle’s Acolyte',exact:true})).toBeEnabled());
    await page.getByRole('button',{name:'Gain Oracle’s Acolyte',exact:true}).click();
    await capture('kept-page','Theseus remains on the same last pile page through Worship and its choice',async()=>{await expect(other.locator('.pile [data-card-id]')).toHaveCount(2);await expect(other.getByRole('button',{name:'New moves · 2 · Refresh',exact:true})).toBeVisible();},true);
    await other.getByRole('navigation',{name:'Public table',exact:true}).getByRole('button',{name:'Chronicle',exact:true}).click();await other.getByRole('button',{name:'New moves · 2 · Refresh',exact:true}).click();
    await capture('topdeck','Athena’s gift names Supply and Deck as its actual path',async()=>{await expect(other.locator('.path')).toHaveText('Supply → Deck');await expect(other.locator('.move [data-card-id]')).toHaveAttribute('data-card-id','oracles-acolyte');},true);
    await other.getByRole('button',{name:'Earlier moves',exact:true}).click();
    await capture('payment','Worship has its own altar source and exact payment',async()=>{await expect(other.locator('.path')).toHaveText('Altar → In play');await expect(other.locator('.result [data-resource=coins]')).toHaveAttribute('data-value','-3');await expect(other.locator('.result [data-resource=worship]')).toHaveAttribute('data-value','-1');},true);
    await other.getByRole('button',{name:'Close',exact:true}).click();await expect(other.getByRole('button',{name:'Chronicle',exact:true})).toBeFocused();
    await page.getByRole('button',{name:'Return',exact:true}).click();await page.getByRole('button',{name:'End turn',exact:true}).click();
    await capture('handoff','Theseus receives the turn while Ariadne’s new cards stay hidden',async()=>{await expect(other.locator('.turn-marker')).toContainText('Your turn');await expect(other.locator('.opponents [data-card-id]')).toHaveCount(0);},true);
    await other.getByRole('button',{name:'Chronicle',exact:true}).click();
    await capture('cleanup','Cleanup and hidden draws persist as backs in the Chronicle',async()=>{await expect(other.locator('.move [data-card-id]')).toHaveCount(0);await expect(other.locator('.move').first()).toHaveAttribute('data-movement','cleanup');await expect(other.locator('.totals')).toContainText('Theseus');},true);
    await other.getByRole('button',{name:'First moves',exact:true}).click();
    await capture('first-move','The beginning of the table is retained alongside gameplay',async()=>expect(other.locator('.chronicle')).toContainText('created the table'),true);
    await other.getByRole('button',{name:'Trash',exact:true}).click();
    await capture('empty-trash','The shared trash is empty and never shows a private deck list',async()=>{await expect(other.locator('.pile')).toHaveText('No cards here.');await expect(other.locator('.public-table [data-card-id]')).toHaveCount(0);},true);
    const state=replaySetup(await readEvents(code));expect(state.publicActivity.at(-1)?.command).toBe('turn/ended');expect(errors).toEqual([]);
  }finally{await context.close();}
});
